# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='optimizer.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdnom', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.IntegerField(default=1)),
                ('m', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=2017)),
                ('h', models.IntegerField(default=8)),
                ('weekday', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='optimizer.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Time'),
        ),
    ]
