# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='y',
        ),
        migrations.AddField(
            model_name='time',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='optimizer.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='m',
            field=models.CharField(max_length=10),
        ),
    ]
