# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_auto_20170725_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='m',
            field=models.IntegerField(max_length=10),
        ),
    ]
