# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_auto_20170725_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='optimizer.Course')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='optimizer.Course')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='constraint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.ConstraintType'),
        ),
    ]
