# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_auto_20170725_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.Project'),
        ),
    ]
