# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0009_auto_20170725_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constraint',
            old_name='type',
            new_name='typec',
        ),
        migrations.RenameField(
            model_name='constrainttype',
            old_name='type',
            new_name='typec',
        ),
    ]
